name: firebase_authentication
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  cloud_firestore: ^3.1.14
  firebase_auth: ^3.3.17
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  icons_launcher: ^1.1.7
  flutter_test: 
    sdk: flutter

flutter_icons:
  image_path: 'assets/images/logo.png'
  ios: true
  android: true
  windows: true

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

